type MonacoThemeData = {
	base: 'vs' | 'vs-dark';
	inherit: boolean;
	rules: { token: string; foreground: string; fontStyle?: string }[];
	colors: Record<string, string>;
};
const dark: MonacoThemeData = {
	base: 'vs-dark',
	inherit: false,
	rules: [
		{ token: '', foreground: 'cdd6f4' },
		{ token: 'comment', foreground: '6c7086', fontStyle: 'italic' },
		{ token: 'comment.doc', foreground: '6c7086', fontStyle: 'italic' },
		{ token: 'string', foreground: 'a6e3a1' },
		{ token: 'string.escape', foreground: 'a6e3a1' },
		{ token: 'keyword', foreground: 'cba6f7', fontStyle: 'bold' },
		{ token: 'keyword.control', foreground: 'cba6f7', fontStyle: 'bold' },
		{ token: 'number', foreground: 'fab387' },
		{ token: 'regexp', foreground: 'f38ba8' },
		{ token: 'type', foreground: '89dceb' },
		{ token: 'class', foreground: '89dceb' },
		{ token: 'function', foreground: '89b4fa' },
		{ token: 'variable', foreground: 'cdd6f4' },
		{ token: 'variable.predefined', foreground: 'f5c2e7' },
		{ token: 'constant', foreground: 'f38ba8' },
		{ token: 'delimiter', foreground: '7f849c' },
		{ token: 'tag', foreground: 'cba6f7' },
		{ token: 'attribute.name', foreground: '89dceb' },
		{ token: 'attribute.value', foreground: 'a6e3a1' },
		{ token: 'metatag', foreground: '7f849c' },
		{ token: 'key', foreground: '89b4fa' }
	],
	colors: {
		'editor.background': '#111624',
		'editor.foreground': '#cdd6f4',
		'editor.selectionBackground': '#598dff4d',
		'editor.inactiveSelectionBackground': '#1e2944',
		'editor.lineHighlightBackground': '#1e294433',
		'editor.lineHighlightBorder': '#00000000',
		'editorCursor.foreground': '#598dff',
		'editorLineNumber.foreground': '#8192b0',
		'editorLineNumber.activeForeground': '#cdd6f4',
		'editorIndentGuide.background1': '#212c47b3',
		'editorIndentGuide.activeBackground1': '#212c47',
		'editorBracketMatch.background': '#598dff1a',
		'editorBracketMatch.border': '#598dff4d',
		'editorGutter.background': '#111624',
		'editorWidget.background': '#171e32c7',
		'editorWidget.foreground': '#cdd6f4',
		'editorWidget.border': '#212c47',
		'editorSuggestWidget.background': '#171e32c7',
		'editorSuggestWidget.border': '#212c47',
		'editorSuggestWidget.foreground': '#cdd6f4',
		'editorSuggestWidget.selectedBackground': '#598dff1a',
		'editorSuggestWidget.selectedForeground': '#cdd6f4',
		'editorSuggestWidget.highlightForeground': '#4577f5',
		'editorHoverWidget.background': '#171e32c7',
		'editorHoverWidget.border': '#212c47',
		'editorHoverWidget.foreground': '#cdd6f4',
		'input.background': '#151c2e',
		'input.foreground': '#cdd6f4',
		'input.border': '#212c47',
		'input.placeholderForeground': '#8192b0',
		focusBorder: '#598dff8c',
		'list.hoverBackground': '#1e2944',
		'list.hoverForeground': '#cdd6f4',
		'list.activeSelectionBackground': '#598dff1a',
		'list.activeSelectionForeground': '#cdd6f4',
		'list.inactiveSelectionBackground': '#1e29444d',
		'list.focusBackground': '#598dff1a',
		'list.focusForeground': '#cdd6f4',
		'list.highlightForeground': '#4577f5',
		'scrollbarSlider.background': '#f1f6fc40',
		'scrollbarSlider.hoverBackground': '#f1f6fc4d',
		'scrollbarSlider.activeBackground': '#f1f6fc66',
		'scrollbar.shadow': '#00000000',
		'dropdown.background': '#171e32c7',
		'dropdown.foreground': '#cdd6f4',
		'dropdown.border': '#212c47'
	}
};
const light: MonacoThemeData = {
	base: 'vs',
	inherit: false,
	rules: [
		{ token: '', foreground: '4c4f69' },
		{ token: 'comment', foreground: '9ca0b0', fontStyle: 'italic' },
		{ token: 'comment.doc', foreground: '9ca0b0', fontStyle: 'italic' },
		{ token: 'string', foreground: '40a02b' },
		{ token: 'string.escape', foreground: '40a02b' },
		{ token: 'keyword', foreground: '8839ef', fontStyle: 'bold' },
		{ token: 'keyword.control', foreground: '8839ef', fontStyle: 'bold' },
		{ token: 'number', foreground: 'fe640b' },
		{ token: 'regexp', foreground: 'd20f39' },
		{ token: 'type', foreground: '04a5e5' },
		{ token: 'class', foreground: '04a5e5' },
		{ token: 'function', foreground: '1e66f5' },
		{ token: 'variable', foreground: '4c4f69' },
		{ token: 'variable.predefined', foreground: 'ea76cb' },
		{ token: 'constant', foreground: 'd20f39' },
		{ token: 'delimiter', foreground: '9ca0b0' },
		{ token: 'tag', foreground: '8839ef' },
		{ token: 'attribute.name', foreground: '04a5e5' },
		{ token: 'attribute.value', foreground: '40a02b' },
		{ token: 'metatag', foreground: '9ca0b0' },
		{ token: 'key', foreground: '1e66f5' }
	],
	colors: {
		'editor.background': '#f8fafc',
		'editor.foreground': '#4c4f69',
		'editor.selectionBackground': '#265de94d',
		'editor.inactiveSelectionBackground': '#e2e8f0b8',
		'editor.lineHighlightBackground': '#e2e8f033',
		'editor.lineHighlightBorder': '#00000000',
		'editorCursor.foreground': '#265de9',
		'editorLineNumber.foreground': '#59687f',
		'editorLineNumber.activeForeground': '#4c4f69',
		'editorIndentGuide.background1': '#e2e8f0b3',
		'editorIndentGuide.activeBackground1': '#e2e8f0',
		'editorBracketMatch.background': '#265de91a',
		'editorBracketMatch.border': '#265de94d',
		'editorGutter.background': '#f8fafc',
		'editorWidget.background': '#ffffffd6',
		'editorWidget.foreground': '#4c4f69',
		'editorWidget.border': '#e2e8f0',
		'editorSuggestWidget.background': '#ffffffd6',
		'editorSuggestWidget.border': '#e2e8f0',
		'editorSuggestWidget.foreground': '#4c4f69',
		'editorSuggestWidget.selectedBackground': '#265de91a',
		'editorSuggestWidget.selectedForeground': '#4c4f69',
		'editorSuggestWidget.highlightForeground': '#1d4ed8',
		'editorHoverWidget.background': '#ffffffd6',
		'editorHoverWidget.border': '#e2e8f0',
		'editorHoverWidget.foreground': '#4c4f69',
		'input.background': '#ffffff',
		'input.foreground': '#4c4f69',
		'input.border': '#e2e8f0',
		'input.placeholderForeground': '#59687f',
		focusBorder: '#265de98c',
		'list.hoverBackground': '#e2e8f0b8',
		'list.hoverForeground': '#4c4f69',
		'list.activeSelectionBackground': '#265de91a',
		'list.activeSelectionForeground': '#4c4f69',
		'list.inactiveSelectionBackground': '#e2e8f04d',
		'list.focusBackground': '#265de91a',
		'list.focusForeground': '#4c4f69',
		'list.highlightForeground': '#1d4ed8',
		'scrollbarSlider.background': '#04070f40',
		'scrollbarSlider.hoverBackground': '#04070f4d',
		'scrollbarSlider.activeBackground': '#04070f66',
		'scrollbar.shadow': '#00000000',
		'dropdown.background': '#ffffffd6',
		'dropdown.foreground': '#4c4f69',
		'dropdown.border': '#e2e8f0'
	}
};
export function createMonacoTheme(): MonacoThemeData {
	return document.documentElement.classList.contains('light') ? light : dark;
}
